#pragma config(Motor,  port5,           chainbarLL,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           chainbarLR,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           chainbarRL,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           chainbarRR,    tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* 1/4 testing each individual chainbar motor */

task main()
{
	while (true)
		{
		if (vexRT[Btn6U] == 1)
		{
			motor[chainbarRR] = 127;
		}
		else
		{
			motor[chainbarRR] = 0;
		}
		if (vexRT[Btn6D] == 1)
		{
			motor[chainbarRL] = 127;
		}
		else
		{
			motor[chainbarRL] = 0;
		}
		if (vexRT[Btn5U] == 1)
		{
			motor[chainbarLL] = 127;
		}
		else
		{
			motor[chainbarLL] = 0;
		}
		if (vexRT[Btn5D] == 1)
		{
			motor[chainbarLR] = 127;
		}
		else
		{
			motor[chainbarLR] = 0;
		}
	}
}
