#pragma config(Motor,  port1,           frontLdrive,   tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           backLdrive,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           backRdrive,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           mogoIntake,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           vertibarL,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           vertibarR,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftL,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           liftR,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          frontRdrive,   tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
-partner control, first controls base and mogo, second controls lift, claw, vertibar
-also program single control
-auton #1: basic preload on stationary goal, then moves back onto parking tile
-auton #2: drive forward, get mogo, stack preload, stack another cone, score 20 point zone
-auton #3: get mogo, preload, 5 point zone
-auton #4: defense/ram auton
-6 motor turbo base, 1 motor mogo intake, 2 motor vertibar (torque), 2 motor lift, 1 motor claw
-y cable 4 motors of the base (4 motor turbo base, 1 high speed motor mogo intake, 2 motor vertibar (torque), 2 high speed motor lift (4 bar 6 bar), 1 torque motor claw)
*/

void pre_auton()
{
	bStopTasksBetweenModes = false;
	bDisplayCompetitionStatusOnLcd = false;
}

task autonomous1()
{

}
task partnercontrol()
{
	while (1 == 1)
	{
		motor[backRdrive] = motor[frontRdrive] = vexRT[Ch2];
		motor[backLdrive] = motor[frontLdrive] = vexRT[Ch3];
		//...and the mogo
		if (vexRT[Btn5U] == 1)
		{
			motor[mogoIntake] = 127;
		}
		if (vexRT[Btn6U] == 1)
		{
			motor[mogoIntake] = -127;
		}
		else
		{
			motor[mogoIntake] = 0;
		}

		//second controller controls the lift...
		motor[liftL] = motor[liftR] = vexRT[Ch2Xmtr2];
		//...vertibar...
		motor[vertibarL] = motor[vertibarR] = vexRT[Ch3Xmtr2];
		//...and the claw
		if (vexRT[Btn6UXmtr2] == 1)
		{
			motor[claw] = 127;
		}
		if (vexRT[Btn5UXmtr2] == 1)
		{
			motor[claw] = 0;
		}
		else
		{
			motor[claw] = -127;
		}
	}
}

task singlecontroller()
{
	while (1 == 1)
	{
		//everything controlled by one controller
		//base code
		motor[backRdrive] = motor[frontRdrive] = vexRT[Ch2];
		motor[backLdrive] = motor[frontLdrive] = vexRT[Ch3];
		//mogo code
		if (vexRT[Btn8R] == 1)
		{
			motor[mogoIntake] = 127;
		}
		if (vexRT[Btn8U] == 1)
		{
			motor[mogoIntake] = -127;
		}
		else
		{
			motor[mogoIntake] = 0;
		}
		//lift
		if (vexRT[Btn6U] == 1)
		{
			motor[liftL] = motor[liftR] = 127;
		}
		if (vexRT[Btn6D] == 1)
		{
			motor[liftL] = motor[liftR] = -127;
		}
		//vertibar
		if (vexRT[Btn7U] == 1)
		{
			motor[vertibarL] = motor[vertibarR] = 127;
		}
		if (vexRT[Btn7L] == 1)
		{
			motor[vertibarL] = motor[vertibarR] = -127;
		}
		else
		{
			motor[vertibarL] = motor[vertibarR] = 0;
		}
		//claw
		if (vexRT[Btn6U] == 1)
		{
			motor[claw] = 127;
		}
		if (vexRT[Btn6D] == 1)
		{
			motor[claw] = -127;
		}
		else
		{
			motor[claw] = 0;
		}
	}
}

task main()
{

}
