#pragma config(Motor,  port2,           backLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           frontRight,    tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* 1/1/2018. Today we decided to change from a 6 motor base to a 4 motor base,
so that we can have more motors for the lift. This is a test for the base motors.*/
task main()
{
	while (true)
	{
		if (vexRT[Btn5U] == 1)
		{
			motor[frontRight] = 127;
		}
		else
		{
			motor[frontRight] = 0;
		}
		if (vexRT[Btn5D] == 1)
		{
			motor[backRight] = 127;
		}
		else
		{
			motor[backRight] = 0;
		}
		if (vexRT[Btn6U] == 1)
		{
			motor[frontLeft] = 127;
		}
		else
		{
			motor[frontLeft] = 0;
		}
		if (vexRT[Btn6D] == 1)
		{
			motor[backLeft] = 127;
		}
		else
		{
			motor[backLeft] = 0;
		}
	}
}
