#pragma config(Motor,  port1,           rightBase,     tmotorVex393HighSpeed_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           vertibarR,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           vertibarL,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mogo,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           topRight,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           topLeft,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           botRight,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           botLeft,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           claw,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          leftBase,      tmotorVex393HighSpeed_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* -lift : 4 HS
	 -vertibar: 2 Torque
	 -claw: 1 HS
	 -claw: 6U, 6D
	 -vertibar: 5U, 5D
	 -lift: 7U, 7L
*/
task main()
{
	while (true)
	{
		motor[leftBase] = vexRT[Ch3];
		motor[rightBase] = vexRT[Ch2];
		if (vexRT[Btn8U] == 1)
		{
			motor[mogo] = 127;
		}
		else if (vexRT[Btn8R] == 1)
		{
			motor[mogo] = -127;
		}
		else
		{
			motor[mogo] = 0;
		}
		if (vexRT[Btn6U] == 1)
		{
			motor[claw] = 127;
		}
		else if (vexRT[Btn6D] == 1)
		{
			motor[claw] = -127;
		}
		else
		{
			motor[claw] = 0;
		}
		if (vexRT[Btn5U] == 1)
		{
			motor[vertibarR] = motor[vertibarL] = 127;
		}
		else if (vexRT[Btn5D] == 1)
		{
			motor[vertibarR] = motor[vertibarL] = -127;
		}
		else
		{
			motor[vertibarR] = motor[vertibarL] = 0;
		}
		if (vexRT[Btn7U] == 1)
		{
			motor[topRight] = motor[topLeft] = motor[botRight] = motor[botLeft] = 127;
		}
		else if (vexRT[Btn7L] == 1)
		{
			motor[topRight] = motor[topLeft] = motor[botRight] = motor[botLeft] = -127;
		}
		else
		{
			motor[topRight] = motor[topLeft] = motor[botRight] = motor[botLeft] = 0;
		}
	}
}
